-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_distribution_log (
  id bigint NOT NULL DEFAULT nextval('ai_distribution_log_id_seq'::regclass),
  exam_id bigint,
  algorithm text NOT NULL,
  input jsonb,
  output jsonb,
  score numeric,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_distribution_log_pkey PRIMARY KEY (id),
  CONSTRAINT ai_distribution_log_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.exams(id),
  CONSTRAINT ai_distribution_log_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.app_settings (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  university_name text DEFAULT 'كلية التمريض · جامعة السلطان قابوس'::text,
  college_name_en text DEFAULT 'College of Nursing'::text,
  college_logo text DEFAULT ''::text,
  academic_year text DEFAULT '2024-2025'::text,
  signature_footer text DEFAULT ''::text,
  pts_morning numeric DEFAULT 1.0,
  pts_afternoon numeric DEFAULT 1.5,
  pts_evening numeric DEFAULT 2.0,
  pts_holiday numeric DEFAULT 1.0,
  pts_long numeric DEFAULT 0.5,
  pts_final_bonus numeric DEFAULT 0.5,
  pts_sem_limit integer DEFAULT 0,
  exam_instructions jsonb DEFAULT '["التحقق من هوية الطلاب قبل البدء", "توزيع أوراق الامتحان بعد الإشارة", "عدم السماح بأي وسيلة تواصل", "تسجيل الغياب في النظام فور انتهاء الامتحان", "جمع أوراق الإجابة مرتبة وموقعة"]'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  email_config jsonb DEFAULT '{"enabled": false, "user_id": "", "provider": "emailjs", "from_name": "ExamFlow", "from_email": "", "service_id": "", "template_id": "template_examflow", "webhook_url": ""}'::jsonb,
  send_exam_report boolean DEFAULT true,
  send_exam_creation boolean DEFAULT true,
  gmail_config jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT app_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.attendance (
  id integer NOT NULL DEFAULT nextval('attendance_id_seq'::regclass),
  exam_id integer NOT NULL,
  student_id integer NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['present'::text, 'absent'::text, 'late'::text, 'excused'::text])),
  recorded_by uuid,
  recorded_at timestamp with time zone DEFAULT now(),
  method text DEFAULT 'manual'::text CHECK (method = ANY (ARRAY['manual'::text, 'qr'::text, 'biometric'::text, 'rfid'::text, 'face'::text])),
  lat double precision,
  lng double precision,
  device_hash text,
  check_in_at timestamp with time zone,
  check_out_at timestamp with time zone,
  verified boolean DEFAULT false,
  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.exams(id),
  CONSTRAINT attendance_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT attendance_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.attendance_events (
  id bigint NOT NULL DEFAULT nextval('attendance_events_id_seq'::regclass),
  exam_id bigint,
  student_id bigint,
  event text NOT NULL,
  method text,
  payload jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attendance_events_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_events_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.exams(id),
  CONSTRAINT attendance_events_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.audit_log (
  id bigint NOT NULL DEFAULT nextval('audit_log_id_seq'::regclass),
  user_id uuid,
  user_name text DEFAULT ''::text,
  action text NOT NULL,
  entity_type text DEFAULT ''::text,
  entity_label text DEFAULT ''::text,
  type text DEFAULT 'info'::text,
  details text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.bookings (
  id integer NOT NULL DEFAULT nextval('bookings_id_seq'::regclass),
  room_id integer NOT NULL,
  booked_by uuid NOT NULL,
  title text NOT NULL,
  purpose text DEFAULT 'lecture'::text,
  date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  recurrence text,
  status text DEFAULT 'confirmed'::text,
  notes text DEFAULT ''::text,
  subject_id integer,
  section_id integer,
  created_at timestamp with time zone DEFAULT now(),
  exam_id integer,
  recurrence_group uuid,
  is_course_booking boolean DEFAULT false,
  semester_schedule_id bigint,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id),
  CONSTRAINT bookings_booked_by_fkey FOREIGN KEY (booked_by) REFERENCES public.profiles(id),
  CONSTRAINT bookings_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id),
  CONSTRAINT bookings_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.sections(id),
  CONSTRAINT bookings_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.exams(id),
  CONSTRAINT bookings_semester_schedule_id_fkey FOREIGN KEY (semester_schedule_id) REFERENCES public.semester_schedules(id)
);
CREATE TABLE public.cross_dept_requests (
  id bigint NOT NULL DEFAULT nextval('cross_dept_requests_id_seq'::regclass),
  exam_id bigint,
  requesting_dept_id bigint,
  target_dept_id bigint,
  requested_by uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  assigned_proctor_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cross_dept_requests_pkey PRIMARY KEY (id),
  CONSTRAINT cross_dept_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.profiles(id),
  CONSTRAINT cross_dept_requests_assigned_proctor_id_fkey FOREIGN KEY (assigned_proctor_id) REFERENCES public.profiles(id),
  CONSTRAINT cross_dept_requests_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.exams(id),
  CONSTRAINT cross_dept_requests_requesting_dept_id_fkey FOREIGN KEY (requesting_dept_id) REFERENCES public.departments(id),
  CONSTRAINT cross_dept_requests_target_dept_id_fkey FOREIGN KEY (target_dept_id) REFERENCES public.departments(id)
);
CREATE TABLE public.departments (
  id integer NOT NULL DEFAULT nextval('departments_id_seq'::regclass),
  name text NOT NULL,
  name_en text DEFAULT ''::text,
  code text NOT NULL UNIQUE,
  head_id uuid,
  color text DEFAULT '#2563eb'::text,
  description text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  coordinator_id uuid,
  CONSTRAINT departments_pkey PRIMARY KEY (id),
  CONSTRAINT departments_head_id_fkey FOREIGN KEY (head_id) REFERENCES public.profiles(id),
  CONSTRAINT departments_coordinator_id_fkey FOREIGN KEY (coordinator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.exam_seals (
  id bigint NOT NULL DEFAULT nextval('exam_seals_id_seq'::regclass),
  exam_id bigint NOT NULL,
  proctor_id uuid,
  proctor_name text,
  timestamp timestamp with time zone DEFAULT now(),
  student_count integer DEFAULT 0,
  exam_type text DEFAULT 'final'::text,
  notes text,
  hash text NOT NULL,
  prev_hash text NOT NULL DEFAULT 'GENESIS'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exam_seals_pkey PRIMARY KEY (id),
  CONSTRAINT exam_seals_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.exams(id),
  CONSTRAINT exam_seals_proctor_id_fkey FOREIGN KEY (proctor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.exams (
  id integer NOT NULL DEFAULT nextval('exams_id_seq'::regclass),
  subject_id integer,
  semester text,
  date date NOT NULL,
  time time without time zone NOT NULL,
  duration integer NOT NULL DEFAULT 120,
  type text NOT NULL CHECK (type = ANY (ARRAY['final'::text, 'midterm'::text, 'quiz'::text, 'makeup'::text])),
  room_ids jsonb DEFAULT '[]'::jsonb,
  proctor_ids jsonb DEFAULT '[]'::jsonb,
  section_ids jsonb DEFAULT '[]'::jsonb,
  room_sections jsonb DEFAULT '{}'::jsonb,
  room_proctors jsonb DEFAULT '{}'::jsonb,
  extra_time integer DEFAULT 0,
  is_holiday boolean DEFAULT false,
  max_grade integer DEFAULT 100,
  notes text DEFAULT ''::text,
  exam_notes jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  end_override timestamp with time zone,
  proctor_statuses jsonb DEFAULT '{}'::jsonb,
  geo_lat double precision,
  geo_lng double precision,
  geo_radius_m integer DEFAULT 50,
  qr_token text,
  qr_expires_at timestamp with time zone,
  allow_biometric boolean DEFAULT true,
  allow_qr boolean DEFAULT true,
  approval_status text DEFAULT 'approved'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  approval_by uuid,
  approval_at timestamp with time zone,
  approval_notes text,
  CONSTRAINT exams_pkey PRIMARY KEY (id),
  CONSTRAINT exams_approval_by_fkey FOREIGN KEY (approval_by) REFERENCES public.profiles(id),
  CONSTRAINT exams_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id),
  CONSTRAINT exams_semester_fkey FOREIGN KEY (semester) REFERENCES public.semesters(code),
  CONSTRAINT exams_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_categories (
  id bigint NOT NULL DEFAULT nextval('notification_categories_id_seq'::regclass),
  name character varying NOT NULL UNIQUE,
  name_ar character varying,
  name_en character varying,
  description text,
  icon character varying,
  color character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_logs (
  id bigint NOT NULL DEFAULT nextval('notification_logs_id_seq'::regclass),
  notification_id bigint,
  user_id uuid NOT NULL,
  sent_at timestamp with time zone DEFAULT now(),
  delivered_at timestamp with time zone,
  read_at timestamp with time zone,
  delivery_status character varying DEFAULT 'pending'::character varying CHECK (delivery_status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'delivered'::character varying, 'failed'::character varying]::text[])),
  delivery_method character varying DEFAULT 'app'::character varying CHECK (delivery_method::text = ANY (ARRAY['app'::character varying, 'email'::character varying, 'sms'::character varying, 'push'::character varying]::text[])),
  CONSTRAINT notification_logs_pkey PRIMARY KEY (id),
  CONSTRAINT notification_logs_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications(id),
  CONSTRAINT notification_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id bigint NOT NULL DEFAULT nextval('notifications_id_seq'::regclass),
  user_id uuid NOT NULL,
  title text NOT NULL,
  body text DEFAULT ''::text,
  type text DEFAULT 'info'::text CHECK (type = ANY (ARRAY['info'::text, 'success'::text, 'warning'::text, 'exam'::text, 'swap'::text])),
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  exam_id bigint,
  read boolean DEFAULT is_read,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT notifications_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.exams(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text DEFAULT ''::text,
  name text NOT NULL,
  role text NOT NULL DEFAULT 'proctor'::text CHECK (role = ANY (ARRAY['admin'::text, 'coordinator'::text, 'dept_head'::text, 'proctor'::text, 'dean'::text, 'assistant_dean'::text])),
  emp_id text DEFAULT ''::text,
  phone text DEFAULT ''::text,
  color text DEFAULT '#1a56db'::text,
  points integer DEFAULT 0,
  sem_x jsonb DEFAULT '{}'::jsonb,
  active boolean DEFAULT true,
  signature text DEFAULT ''::text,
  dept_id integer,
  lang text DEFAULT 'ar'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  signature_updated_at timestamp with time zone,
  is_inactive boolean DEFAULT false,
  lang_pref text DEFAULT 'ar'::text,
  avg_rating double precision DEFAULT 0,
  ratings jsonb DEFAULT '[]'::jsonb,
  permissions jsonb,
  password text DEFAULT ''::text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_dept_id_fk FOREIGN KEY (dept_id) REFERENCES public.departments(id)
);
CREATE TABLE public.push_subscriptions (
  id bigint NOT NULL DEFAULT nextval('push_subscriptions_id_seq'::regclass),
  user_id uuid NOT NULL,
  endpoint text NOT NULL,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.rooms (
  id integer NOT NULL DEFAULT nextval('rooms_id_seq'::regclass),
  name text NOT NULL,
  type text DEFAULT 'classroom'::text CHECK (type = ANY (ARRAY['lecture'::text, 'lab_comp'::text, 'lab_sci'::text, 'classroom'::text, 'hall'::text, 'seminar'::text, 'simulation'::text, 'other'::text])),
  building text DEFAULT ''::text,
  floor text DEFAULT ''::text,
  cap integer DEFAULT 30,
  notes text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  geo_lat double precision,
  geo_lng double precision,
  geo_radius_m integer DEFAULT 50,
  CONSTRAINT rooms_pkey PRIMARY KEY (id)
);
CREATE TABLE public.schedules (
  id integer NOT NULL DEFAULT nextval('schedules_id_seq'::regclass),
  subject_id integer NOT NULL,
  section_id integer,
  room_id integer,
  instructor_id uuid,
  semester text,
  day_of_week smallint NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  type text DEFAULT 'lecture'::text CHECK (type = ANY (ARRAY['lecture'::text, 'lab'::text, 'tutorial'::text, 'seminar'::text])),
  is_recurring boolean DEFAULT true,
  notes text DEFAULT ''::text,
  color text DEFAULT '#2563eb'::text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT schedules_pkey PRIMARY KEY (id),
  CONSTRAINT schedules_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id),
  CONSTRAINT schedules_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.sections(id),
  CONSTRAINT schedules_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id),
  CONSTRAINT schedules_instructor_id_fkey FOREIGN KEY (instructor_id) REFERENCES public.profiles(id),
  CONSTRAINT schedules_semester_fkey FOREIGN KEY (semester) REFERENCES public.semesters(code),
  CONSTRAINT schedules_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.sections (
  id integer NOT NULL DEFAULT nextval('sections_id_seq'::regclass),
  name text NOT NULL,
  subject_id integer,
  coord_id uuid,
  semester text,
  student_ids jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  staff_ids jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT sections_pkey PRIMARY KEY (id),
  CONSTRAINT sections_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id),
  CONSTRAINT sections_coord_id_fkey FOREIGN KEY (coord_id) REFERENCES public.profiles(id),
  CONSTRAINT sections_semester_fkey FOREIGN KEY (semester) REFERENCES public.semesters(code)
);
CREATE TABLE public.semester_schedules (
  id bigint NOT NULL DEFAULT nextval('semester_schedules_id_seq'::regclass),
  semester text NOT NULL,
  subject_id bigint,
  section_id bigint,
  room_id bigint,
  instructor_id uuid,
  day_of_week smallint NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  type text DEFAULT 'lecture'::text,
  notes text,
  auto_book boolean DEFAULT true,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT semester_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT semester_schedules_instructor_id_fkey FOREIGN KEY (instructor_id) REFERENCES public.profiles(id),
  CONSTRAINT semester_schedules_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id),
  CONSTRAINT semester_schedules_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.sections(id),
  CONSTRAINT semester_schedules_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id)
);
CREATE TABLE public.semesters (
  code text NOT NULL,
  label text NOT NULL,
  is_active boolean DEFAULT false,
  is_closed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT semesters_pkey PRIMARY KEY (code)
);
CREATE TABLE public.staff_credentials (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  credential_id text NOT NULL UNIQUE,
  public_key text NOT NULL,
  device_label text DEFAULT 'device'::text,
  last_used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT staff_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT staff_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.student_credentials (
  id bigint NOT NULL DEFAULT nextval('student_credentials_id_seq'::regclass),
  student_id bigint NOT NULL,
  credential_id text NOT NULL UNIQUE,
  public_key text NOT NULL,
  counter bigint DEFAULT 0,
  device_label text,
  created_at timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone,
  CONSTRAINT student_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT student_credentials_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.students (
  id integer NOT NULL DEFAULT nextval('students_id_seq'::regclass),
  stud_id text NOT NULL UNIQUE,
  name text NOT NULL,
  batch integer DEFAULT 2024,
  email text DEFAULT ''::text,
  phone text DEFAULT ''::text,
  active boolean DEFAULT true,
  banned boolean DEFAULT false,
  subject_ids jsonb DEFAULT '[]'::jsonb,
  section_ids jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  pin text DEFAULT ''::text,
  photo_url text DEFAULT ''::text,
  password text,
  CONSTRAINT students_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subjects (
  id integer NOT NULL DEFAULT nextval('subjects_id_seq'::regclass),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  level text DEFAULT ''::text,
  hours integer DEFAULT 3,
  dept_id integer,
  created_at timestamp with time zone DEFAULT now(),
  staff_ids jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT subjects_pkey PRIMARY KEY (id),
  CONSTRAINT subjects_dept_id_fkey FOREIGN KEY (dept_id) REFERENCES public.departments(id)
);
CREATE TABLE public.supervision_requests (
  id integer NOT NULL DEFAULT nextval('supervision_requests_id_seq'::regclass),
  proctor_id uuid NOT NULL,
  exam_id integer NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  reason text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT supervision_requests_pkey PRIMARY KEY (id),
  CONSTRAINT supervision_requests_proctor_id_fkey FOREIGN KEY (proctor_id) REFERENCES public.profiles(id),
  CONSTRAINT supervision_requests_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.exams(id)
);
CREATE TABLE public.swap_requests (
  id integer NOT NULL DEFAULT nextval('swap_requests_id_seq'::regclass),
  requester_id uuid NOT NULL,
  target_id uuid NOT NULL,
  exam_id integer NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  reason text DEFAULT ''::text,
  response text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT swap_requests_pkey PRIMARY KEY (id),
  CONSTRAINT swap_requests_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES public.profiles(id),
  CONSTRAINT swap_requests_target_id_fkey FOREIGN KEY (target_id) REFERENCES public.profiles(id),
  CONSTRAINT swap_requests_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.exams(id)
);
CREATE TABLE public.user_bookings (
  id bigint NOT NULL DEFAULT nextval('user_bookings_id_seq'::regclass),
  user_id uuid NOT NULL,
  booking_id bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT user_bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_bookings_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);